import ContactPage from './pages/ContactPage';
import LoginPage from './pages/LoginPage';

describe('Contact Page', () => {
  beforeEach(() => {
    cy.fixture('credential').then((creds) => {
      LoginPage.visit();
      LoginPage.fillEmail(creds.valid.email);
      LoginPage.fillPassword(creds.valid.password);
      LoginPage.clickSignIn();
      cy.wait(2000);
    });
    ContactPage.visit();
    cy.wait(1000);
  });

  it('should display Contact UI', () => {
    ContactPage.checkUI();
  });

  it('should submit question and show success notification', () => {
    ContactPage.fillSubject('Test question about Nebula Block platform');
    ContactPage.fillDescription('This is a test question generated by automation. Please ignore. How can I use the API for batch inference?');
    ContactPage.submit();
    ContactPage.checkSuccessNotification();
  });
}); 