import ContactPage from './pages/ContactPage';
import LoginPage from './pages/LoginPage';
import { ENDPOINTS } from '../support/constants';

describe('Contact Page', () => {
  beforeEach(() => {
    cy.fixture('credential').then((creds) => {
      LoginPage.visit();
      LoginPage.login(creds.valid.email, creds.valid.password);
      LoginPage.isLoggedIn(creds.valid.username);
      cy.url().should('include', ENDPOINTS.SERVERLESS);
    });
    ContactPage.visit();
    cy.url().should('include', ENDPOINTS.CONTACT);
  });

  it('should display Contact UI', () => {
    ContactPage.checkUI();
  });

  it('should submit contact form', () => {
    ContactPage.fillSubject('Test question about Nebula Block platform');
    ContactPage.fillDescription('This is a test question generated by automation. Please ignore. How can I use the API for batch inference?');
    ContactPage.submit();
    ContactPage.checkSuccessNotification();
  });
}); 