name: Run Cypress Tests and Publish Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        user: action/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        user: action/checkout@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up url
         run: |
          echo '{
            "baseUrlStaging": "'"${{secrets.STAGING_BASE_URL }}"'"
          }' > cypress.env.json

      - name: Run test and merge report in dev environment
        run: |
          npm run test:staging
          npm run report:merge:staging
        env:
          ENV: staging

    